examples/sdl_audio_callback.nim

Ensures that we are writing to the buffer size SDL actually returned.

Use obtained audioSpec data

---

src/sdl2.nim
src/sdl2/image.nim

I don't understand the DestroyWindow one quite. Did it work before?

Fix small bugs

---

examples/sdl_opengl_example.nim

Update the OpenGL example to fix some deprecation warnings and handle window resizing correctly.

Update OpenGL example

---

src/sdl2/haptic.nim

Loads of comments. They bother me but the original had them.

Added wrapper for haptic

---

src/sdl2/private/keycodes.nim

Another constant fix. K_DELETE.

---

src/sdl2.nim

add rwops functions

---

examples/sdl_mixer_example.nim
src/sdl2/mixer.nim

I've included an example as well, I've only tested on windows 7 so if anyone's willing to test this on linux/mac that would be great.
Binaries can be found here: https://www.libsdl.org/projects/SDL_mixer/

Added SDL2_Mixer support

---

src/sdl2/gfx.nim
src/sdl2/image.nim
src/sdl2/mixer.nim
src/sdl2/net.nim
src/sdl2/ttf.nim

Fedora has different naming for libraries.

Add library manes to match Fedora naming

---

src/sdl2/net.nim

This is the name provided in the binaries located [here](https://www.libsdl.org/projects/SDL_net/)

Added windows name

---

src/sdl2/mixer.nim

Moved the template declaration of playChannel proc below playChannelTimed to fix compile error.

Fix playChannel template declaration

---

src/sdl2.nim

Added MouseWheelDirection

---

src/sdl2.nim

Also fixes some capitalization.

Allow the remaining nil Rect arguments.

---

src/sdl2.nim
src/sdl2/audio.nim
src/sdl2/gamecontroller.nim
src/sdl2/gfx.nim
src/sdl2/haptic.nim
src/sdl2/image.nim
src/sdl2/joystick.nim
src/sdl2/mixer.nim
src/sdl2/net.nim
src/sdl2/ttf.nim

Please note that I haven't extensively tested this.

Deprecate SDL_Static flag. Fixes #87, #88.

---

sdl2.nimble
src/sdl2.nim

Add missing SDL_WINDOW_VULKAN constant

---

src/sdl2.nim

https://wiki.libsdl.org/SDL_RenderSetClipRect

added renderer clipRect methods

---

README.md

Including necessary options to statically link SDL2.
I'm new to Nim so I'm not sure if everything is exactly correct, but it worked in my case and helped me build and statically link a project which uses [nimx](https://github.com/yglukhov/nimx).

Update README.md with information for Windows

---

src/sdl2.nim

Fix typo SDL_GetNumRenderDriver -> SDL_GetNumRenderDrivers

Fix getNumRenderDrivers

---

src/sdl2.nim

I made a mistake in #128, this is the correct version.

Properly fix #126

---

src/sdl2.nim

I had to use this for a project, thought it was odd not being included in the library. Easy drop-in.

Add updateYUVTexture(), a binding to SDL_UpdateYUVTexture()

---

src/sdl2/audio.nim

add SDL_DequeueAudio see
https://wiki.libsdl.org/SDL_QueueAudio

Add dequeue audio

---

README.md

Just adds a small readme snippet for macOS users that prefer macports to brew (like me ;))

Add macports instructions

---

src/sdl2.nim

add extra library name check for haiku

---

src/sdl2/ttf.nim

fixes #147

---

src/sdl2.nim

Note: The minimum version of SDL2 supported after these changes would be SDL 2.0.10. I'm not sure what the minimum version supported is currently. Also not sure if it's cool to just make a PR without speaking with anyone first, but let me know if it's an issue, please. ❤️

Add float rendering funcs and corresponding types. Fix csize warnings.

---

src/sdl2/joystick.nim

Hello
This pull request adds bindings for some missing joystick functions.

Add missing joystick procs

---

src/sdl2/gamecontroller.nim

Hello
This pull request adds bindings for some missing gamecontroller functions.

feat: add some missing functions for game controllers
