nim-lang/sdl2

src/sdl2/gamecontroller.nim
src/sdl2/joystick.nim

Adds a new module, gamecontroller.nim, with bindings for the SDL_GameController functions and types. Also fixes compile errors in the joystick module, which this module depends on.

SDL_GameController bindings

---

src/sdl2/image.nim

I couldn't use the SDL2_Image class, so I added support. (yay first contribution)

Added support for windows to use SDL2_image.dll

---

src/sdl2.nim

Wrong name in C function. 'b' in 'callback' lowercased.

Fixed iPhoneSetAnimationCallback

---

src/sdl2.nim

If I understood correctly, KeyReleased and KeyPressed constants are counterparts of SDL_RELEASED and SDL_PRESSED in C. In such case, they are incorrect. Here's a few lines from SDL_events.h:
```
/* General keyboard/mouse state definitions */
#define SDL_RELEASED    0
#define SDL_PRESSED 1
```

Fixed KeyReleased and KeyPressed constants

---

src/sdl2/gfx.nim

When entering the colors as a single integer as opposed to composing them using SDL_FOURCC the byte order is reversed. (Note that this differs from the Colors module in the Nim standard library which use 0x00RRGGBB.)

changed color order in comment

---

src/sdl2.nim

Fixes a crash when using RWops.

Use C calling conventions for callbacks.

---

src/sdl2/ttf.nim

Probably got messed up when def was fixing the SDL_Static casing.

Fixed ttf not properly including libraries

---

src/sdl2.nim

We have noticed in our team that dependency on `SDL.h` is not really needed and just requires more steps to properly set up search paths.

Removed depency on header file

---

src/sdl2.nim

Workaround fix for calling setDrawColor with explicit arguments.
Example: renderer.setDrawColor(r=0, g=0, b=0, a=255)

Fix for issue #62

---

src/sdl2.nim

There were some missing enums for use with `glSetAttribute`. They're defined as `const` rather than an `enum` so they'll typecheck with the function as it exists right now.

Added Missing SDL2 Enums

---

src/sdl2.nim

I encountered an issue where my Joystick axis wasn't registering.
According to https://hg.libsdl.org/SDL/file/e12c38730512/include/SDL_joystick.h#l72 it should be an int32 rather than uint8.
Changing this got the joystick axis to work.

SDL_JoystickId is int32

---

src/sdl2/mixer.nim

Defining the initFlags as an enum requires awkward casting to 'or' flags together and pass them into mixer.init().  It is also inconsistent with how the flags are defined for other subsystems.
This pull just changes the flags to public consts.

Changed mixer initFlags from enum to consts

---

src/sdl2/image.nim

This PR adds the IMG_SavePNG function. 
Every one ends up using it or implementing one at some point. The controversial part is that this function is not "documented." But is really useful otherwise you have to import another library.
Its been with SDL since 02 Jun 2013 and ton of people have used it..
https://hg.libsdl.org/SDL_image/rev/cf211e9ff224

Add IMG_SavePNG

---

src/sdl2.nim

This improves the code:
* templates are a bit more type safe (more than the original C version)
* templates appear now less often in nimsuggest siggestions
* deprecated functionality is now replaced

added types to templates

---

src/sdl2.nim

These are missing and required for detecting various subsystems via SDL2.

Adding missing SysWMType entries

---

src/sdl2/mixer.nim
src/sdl2/private/keycodes.nim

I replaced the ``expr`` keyword with untyped. I'm not sure if I should be using ``typed`` in some of these cases or not.

Remove deprecated expr

---

README.md

Added a simple README because I wanted to document a bit about using this.
For other people, as it was for me, the SDL2 bindings might be the first serious exposure to nimble. I was considering adding some quick documentation about how to create a nimble file using `nimble init` but wasn't sure if that was too much detail that would add to maintenance later if nimble ever changed.
For now, I've just documented the native dependencies and said a little blurb.

Created the bones of a README

---

src/sdl2.nim

The correct symbol name is `SDL_Vulkan_GetVkGetInstanceProcAddr`

Fixes typo

---

src/sdl2.nim

/cc @krux02 
fixes regression introduced in d0537fcc7da798afb94d76331b92fed2ee184e74

fix regression: invalid proc quit()* => proc quit*()

---

src/sdl2.nim

- Added missing event types.
- Fixed `WMInfo` padding size to match that of `SDL_SysWMinfo` in `SDL_syswm.h`.

Added more events. Fixed SysWMInfo size.

---

src/sdl2.nim

... because `when defined(ios)` is the way for nim stdlib to determine ios.

Added missing WindowEvents, enable iphone api when defined(ios)

---

sdl2.nimble

(a prior git tag was published at 2.0 the forced-pushed again at 2.0 after new commits; even though it may affect not many users, there's no reason to re-released a published version as was done here: https://github.com/nim-lang/sdl2/pull/112#issuecomment-436763824 )
rationale:
see comment from @Araq  here: https://github.com/nim-lang/sdl2/issues/113#issuecomment-437152083
> The Nimble version shouldn't be based on the version of the originally wrapped library, that ignores how the Nim wrapping mechanism works. Only accessed symbols are dlsym'ed so wrapping SDL 2.0.10 and accessing a SDL_2.0.1.dll works as long as you don't use a feature that 2.0.1 lacks.
supersedes https://github.com/nim-lang/sdl2/pull/112 and https://github.com/nim-lang/sdl2/issues/113

bump version because of prior bugfix after a published release

---

src/sdl2.nim

Related to https://github.com/nim-lang/Nim/pull/12143 - OpenBSD creates `/usr/local/lib/libSDL2.so.0.6` when using `pkg_add sdl2`, but not `/usr/local/lib/libSDL2.so`.

Update lib name on OpenBSD

---

examples/sdl_audiostream.nim
sdl2.nimble
src/sdl2/audio.nim

I have added calls for the SDL2 Audio Stream API. Audio streams were added in 2.0.7, and provide a much easier-to-use alternative to AudioCVT. Unfortunately, the SDL2 wiki has not yet updated to show the docs for these functions, but the SDL2 source code has doc comments, so I took the doc comments and adapted them to Nim.
New types:
- `AudioStream`: Nim representation of the _SDL2_AudioStream struct. This struct's contents are not visible to library users, so I have made its implementation private in the Nim package, as well.
- `AudioStreamPtr` pointer to AudioStream. These get handed to API users.
New procs:
```nim
proc newAudioStream*(
src_format: AudioFormat;
src_channels: uint8;
src_rate: cint;
dst_format: AudioFormat;
dst_channels: uint8;
dst_rate: cint): AudioStreamPtr {.importc: …
```

Add Audio Streams API, docs, example

---

src/sdl2.nim
src/sdl2/gfx.nim

I changed the pattern of the main library to support versioned names so you don't need to install development packages to run the application. I also changed the pattern of SDL2_gfx because it uses a different versioning scheme which is reflected in the so name.

Fix Linux library patterns.

---

src/sdl2.nim

Hello
This commit adds bindings for `setIntegerScale` and `getIntegerScale` which should fix issue https://github.com/nim-lang/sdl2/issues/151

fix: add `setIntegerScale` and `getIntegerScale`

---

src/sdl2/gamecontroller.nim

Hello
@Araq 
this pr does three small things, one per commit:
1. [481de45](https://github.com/BarrOff/sdl2/commit/481de4502cb1d587c554a7e52e7e091e28f3575d) fixes a typo in a parameter type (I used `Uint32` instead of `uint32`)
2. [98d8ce9](https://github.com/BarrOff/sdl2/commit/98d8ce953db06e623f12bd7a285c7b7358862621) partly reverts my [commit](https://github.com/nim-lang/sdl2/commit/a71b87524a25bb6c0a9b0e2821a922bb62bd316b) which removed the `gameController` prefix from some procs. I found this to cause multiple problems:
- this was a backwards incompatible change
- I did not change it in all places so there were remains using the old names
- it does not seem to suit the naming conventions. Looking at the [joystick code](https://github.com/nim-lang/sdl2/blob/master/src/sdl2/joystick.nim) …

fix: lower case first letter of type
